### ISSUE TITLE
freeze during downloading comments

### ISSUE THREAD

**Issue by Roechiiii** [sachin-bisht/YouTube-Sentiment-Analysis#1]
Hey, first of all nice work! I tried your code to download some comments and it works pretty good in the most cases, but as I tried your code on YouTube-Sites that contains thousands of comments such as PewDiePie-videos, the downloading process seems like to freeze.

I used the following videoID:
`comments = commentExtract("jvO1GDJXOgo")
print(comments)`

**Comment by sachin-bisht** [comment]
Thanks! Sorry for the late reply(very late actually). The freeze that happened during downloading comments is status error 429. It happens when we send too many requests. Even though I use the YouTube-API the error still happens. One alternative is to use different APIs at one time. If you find other best alternative tell me also :)
